# Generated by Django 5.0.6 on 2025-03-23 13:28

import config.utils.image_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_rename_product_categoryimage_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryimage',
            name='image',
            field=models.ImageField(upload_to='categories/', validators=[config.utils.image_validators.validate_image_resolution, config.utils.image_validators.validate_image_size]),
        ),
    ]
