# Generated by Django 5.0.6 on 2025-03-23 11:24

import config.utils.image_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_product_active_alter_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products/', validators=[config.utils.image_validators.validate_image_resolution, config.utils.image_validators.validate_image_size]),
        ),
    ]
